name: Apply Product Service Deployment
on:
  push:
    branches: [main]
  paths:
      - sharetopia-product-service-deployment.yaml

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

- name: Deploy to Kubernetes cluster
  uses: kodermax/kubectl-aws-eks@master
  with:
    args: apply -f sharetopia-product-service-deployment.yaml